pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm ci'

  - script: npm build
    displayName: 'npm build'

  - script: npm run lint
    displayName: 'npm run lint'

  - script: npm test with coverage
    displayName: 'npm test:coverage'
